Improvements
jumaffre/cimetrics pull request #36
Opened 2019-08-19 20:55 UTC by jumaffre

- Does not fail horribly if `metrics.yml` file does not exist.
- Create report graph on git environment (i.e. local env, not a PR) and compare to `master` branch by default, except if `CIMETRICS_TARGET_BRANCH` env var is set.

2019-08-19 20:56 UTC, cimetrics commented
![images](https://raw.githubusercontent.com/jumaffre/cimetrics/cimetrics/cimetrics/image2019-08-19%2020%3A56%3A10.372144.png)

2019-08-19 21:07 UTC, cimetrics commented
![images](https://raw.githubusercontent.com/jumaffre/cimetrics/cimetrics/cimetrics/image2019-08-19%2021%3A07%3A03.082864.png)

2019-08-19 21:12 UTC, cimetrics commented
![images](https://raw.githubusercontent.com/jumaffre/cimetrics/cimetrics/cimetrics/image2019-08-19%2021%3A12%3A23.981826.png)

2019-08-19 21:35 UTC, cimetrics commented
![images](https://raw.githubusercontent.com/jumaffre/cimetrics/cimetrics/cimetrics/image2019-08-19%2021%3A35%3A29.617650.png)

2019-08-19 21:35 UTC, jumaffre commented
/azp run

2019-08-19 21:36 UTC, cimetrics commented
![images](https://raw.githubusercontent.com/jumaffre/cimetrics/cimetrics/cimetrics/image2019-08-19%2021%3A36%3A35.647870.png)

2019-08-19 21:40 UTC, achamayou requested changes

2019-08-19 21:40 UTC, achamayou commented on cimetrics/env.py
> +        target_branch_ = os.environ.get("SYSTEM_PULLREQUEST_TARGETBRANCH")
.get() takes a default, it’s shorter to pass it and return the result directly.

2019-08-19 21:40 UTC, achamayou commented on cimetrics/upload.py
> +        except:
Never except:, except Exception at worst, but here we should really be more precise. We don’t want to hide a permission issue for example.

2019-08-19 21:41 UTC, cimetrics commented
![images](https://raw.githubusercontent.com/jumaffre/cimetrics/cimetrics/cimetrics/image2019-08-19%2021%3A41%3A33.821099.png)

2019-08-20 08:09 UTC, cimetrics commented
![images](https://raw.githubusercontent.com/jumaffre/cimetrics/cimetrics/cimetrics/image2019-08-20%2008%3A09%3A08.188914.png)

2019-08-20 08:13 UTC, cimetrics commented
![images](https://raw.githubusercontent.com/jumaffre/cimetrics/cimetrics/cimetrics/image2019-08-20%2008%3A13%3A37.163495.png)

2019-08-20 08:16 UTC, jumaffre commented
Merging this now as I believe that the feedback has been addressed and some changes are necessary for CCF. Will continue further improvements/refactoring in further PRs.

2019-08-20 08:16 UTC, merged